In [2]:
import numpy as np

In [11]:
# CREATING AN 0-D ARRAY
arr0 = np.array(90)
print(arr0)

90


In [12]:
# CREATING AN 1-D ARRAY
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [9]:
# CREATING AN 2-D ARRAY
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)

[[1 2 3]
 [2 3 4]]


In [15]:
# CHEKING DIMENSION OF THE ARRAY
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)

0
1
2


In [18]:
# TO FIND NUMBER OF ELEMENTS IN ARRAY
print(arr0.size)
print(arr1.size)
print(arr2.size)

1
5
6


In [19]:
# TOTAL MEMORY TAKEN BY AN ARRAY
print(arr0.nbytes)
print(arr1.nbytes)
print(arr2.nbytes)

4
20
24


In [21]:
# SINGLE ELEMENT SIZE
print(arr0.itemsize)
print(arr1.itemsize)
print(arr2.itemsize)

4
4
4


In [22]:
# TO FIND DATATYPE OF ARRAY
print(arr0.dtype)
print(arr1.dtype)
print(arr2.dtype)

int32
int32
int32


In [23]:
# FOR A SPECIFIC ELEMENT OF AN ARRAY
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [26]:
arr2[1,1]

3

In [28]:
# SPECIFIC ROW OF ARRAY
arr2[1]

array([2, 3, 4])

In [ ]:
# SLICING

In [3]:
# FEW RANGE BETWEEN ARRAY ELEMENTS
arr3 = np.array([1,2,3,4,5,6,7,8,9])
print(arr3)

[1 2 3 4 5 6 7 8 9]


In [7]:
# arr3[start_of_index : end_of_index]
# arr3[inclusive : exclusive]
# Last end index ko ye exclude krega

print(arr3[1:5])
print(arr3[3:])

[2 3 4 5]
[4 5 6 7 8 9]


In [10]:
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [15]:
# arr2[row_num , start_index : end_index]
arr2[1, 1:2]

array([3])

In [16]:
# COPY AN ARRAY
arr4 = arr2.copy()
print(arr4)

[[1 2 3]
 [2 3 4]]


In [17]:
# ZERO MATRIX
# np.zeros((row, column))
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# ONE MATRIX
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [22]:
# ANOTHER NUMBER MATRIX
# ((row, col), number)
np.full((4,4), 56)

array([[56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56]])

In [23]:
# DECIMAL NUMBER ARRAY CREATION
# importing random

from numpy import random

In [26]:
np.random.rand(4,3)

array([[0.07648743, 0.10618994, 0.06556714],
       [0.33870153, 0.31521967, 0.10662498],
       [0.61691493, 0.55661136, 0.75205344],
       [0.97645271, 0.90592228, 0.52551357]])

In [28]:
# IDENTITY MATRIX
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
# MATHEMATICAL OPERATIONS
arrm = np.array([10,20,30,40,50])
arrm

array([10, 20, 30, 40, 50])

In [31]:
arrm+12

array([22, 32, 42, 52, 62])

In [32]:
arrm-10

array([ 0, 10, 20, 30, 40])

In [33]:
arrm*10

array([100, 200, 300, 400, 500])

In [34]:
arrm/10

array([1., 2., 3., 4., 5.])

In [35]:
# with arrays
a1 = np.array([1,2,3])
a2 = np.array([1,1,1])

a3 = a1+a2
a3

array([2, 3, 4])

In [36]:
# COS
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [37]:
# MIN MAX VALUE FROM ARRAY

arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [38]:
np.min(arr2)

1

In [39]:
np.max(arr2)

4

In [40]:
# SUM OF ARRAY
np.sum(arr2)

15

In [41]:
# Iterating in 2-D
for z in arr2:
  print(z)

[1 2 3]
[2 3 4]


In [42]:
for y in arr2:
  for z in y:
    print(z)

1
2
3
2
3
4
